--- File

CREATE TABLE IF NOT EXISTS file_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT
,   event_id INTEGER NOT NULL
,   info_id INTEGER NOT NULL
,   kind TEXT
);

CREATE TABLE IF NOT EXISTS file_info (
    id INTEGER PRIMARY KEY AUTOINCREMENT
,   path TEXT NOT NULL
);
